In [1]:
import pandas as pd
df = pd.read_csv('car_sales_cleaned1.csv')
df

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,Male,13500,Ford,Expedition,Auto,Black,26000
1,Male,1480000,Dodge,Durango,Auto,Black,19000
2,Male,1035000,Cadillac,Eldorado,Manual,Red,31500
3,Male,13500,Toyota,Celica,Manual,Pale White,14000
4,Male,1465000,Acura,TL,Auto,Red,24500
...,...,...,...,...,...,...,...
23901,Male,13500,Plymouth,Voyager,Manual,Red,12000
23902,Female,900000,Chevrolet,Prizm,Auto,Black,16000
23903,Male,705000,BMW,328i,Manual,Red,21000
23904,Male,13500,Chevrolet,Metro,Auto,Black,31000
23905,Male,1225000,Lexus,ES300,Auto,Pale White,27500

In [2]:
df.describe()

       Annual Income     Price ($)
count   2.390600e+04  23906.000000
mean    8.308403e+05  28090.247846
std     7.200064e+05  14788.687608
min     1.008000e+04   1200.000000
25%     3.860000e+05  18001.000000
50%     7.350000e+05  23000.000000
75%     1.175750e+06  34000.000000
max     1.120000e+07  85800.000000

In [4]:
df = df.drop_duplicates()
df.shape

(20358, 7)

In [5]:
df = df.dropna() # drop rows with null values
df.shape

(20358, 7)

In [6]:
company_values = df['Company'].unique()
company_values

array(['Ford', 'Dodge', 'Cadillac', 'Toyota', 'Acura', 'Mitsubishi',
       'Chevrolet', 'Nissan', 'Mercury', 'BMW', 'Chrysler', 'Subaru',
       'Hyundai', 'Honda', 'Infiniti', 'Audi', 'Porsche', 'Volkswagen',
       'Buick', 'Saturn', 'Mercedes-B', 'Jaguar', 'Volvo', 'Pontiac',
       'Lincoln', 'Oldsmobile', 'Lexus', 'Plymouth', 'Saab', 'Jeep'],
      dtype=object)

In [7]:
df_proj = df[['Annual Income','Price ($)']]
df_proj

       Annual Income  Price ($)
0              13500      26000
1            1480000      19000
2            1035000      31500
3              13500      14000
4            1465000      24500
...              ...        ...
23898         530000      24000
23900         771000      19000
23902         900000      16000
23903         705000      21000
23905        1225000      27500

[20358 rows x 2 columns]

In [32]:
from sklearn.tree import DecisionTreeClassifier
model_price_income = DecisionTreeClassifier()
x = df_proj[['Price ($)']]
y = df_proj[['Annual Income']]
model_price_income.fit(y, x)
predictions = model_price_income.predict([[31500]])
predictions

C:\Users\ageres\miniconda3\envs\ai_env\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([61001])